print("\n\t\t\t\t\t\t""  Hello student!")
print("\n\t\t\t\t\t\t\t""I am beep!")
print("\n\t\t\t\t\t\t""What is your name?")
name=input()
print("\n""PROBLEM IN THE SYSTEM PLEASE PRESS ANY KEY IF YOU WANT TO COUNTINUE")
press=input()
print("System reboot has been initiated...")
print()
print()
print("...rebooting sensory system")
print("...rebooting output motors")
print("...rebooting hover engine")
print()
print("\n""Please enter the number of lives")
lives=int(input())
print("\n""Please enter the energy level")
level=int(input())
print("\n""Please enter the shield level")
shield=int(input())
print("\n""Health has been set")
print("\n""Lives:  ",lives*"♥" )
print("Energy: ",level*"♦" )
print("Shield: ",shield*"۩")
print("\n\n""System online.")
print("""
What is your mood?
For happy press ^
For sad press o 
""")
eye=input()
print("##########")
print("#  "+ eye +"  "+ eye +"  #")
print("#  ----  #")
print("##########")
print("\n""Nice to meet you", name, "!")
print("\n""What is your course?")
course=input()
print("Crazy, I am in the same course:", course)
print("\n""Low battery, I want to sleep please shutdown me!")
shutdown=input("\n""SHUTDOWN")
print()
print("##########")
print("#  z  z  #")
print("#  ----  #")
print("##########")
print()
print()
print("Good night! zzzzzzzz")