print("\n""Please enter the number of lives")
lives=int(input())
print("\n""Please enter the energy level")
level=int(input())
print("\n""Please enter the shield level")
shield=int(input())
print("\n""Health has been set")
print("\n""Lives:  ",lives*"♥" )
print("Energy: ",level*"♦" )
print("Shield: ",shield*"۩")